### ISSUE TITLE
How to test if the `content-type` header of a given URL matches e.g. `text/html`?

### ISSUE THREAD

**Issue by mathiasbynens** [cgiffard/Behaviour-Assertion-Sheets#11]
Is it possible to test if the `content-type` header of a given URL contains, say, `text/html`, and matches `/utf-8/i` too?

I was trying this:

``` css
@page (path = /index.php) {
  status-code: 200;
  content-type: contains('text/html'), /utf-8/i;
}
```

…but it seems it doesn’t work that way:

```
    1 failed assertions:
        'content-type' expects contains('text/html'), /utf-8/i: Component test 'contains' failed against input 'text/html'.
```
